name: Karate Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew test
      - name: Generate Cucumber HTML Report
        run: |
          ./gradlew generateCucumberReport
          mkdir -p cucumber-reports
          cp -r build/cucumber-reports/html/overview-features.html cucumber-reports/
      - uses: actions/upload-artifact@v2
        with:
          name: cucumber-reports
          path: cucumber-reports